export const minerActorCodes = [
  'send',
  'constructor',
  'control addresses',
  'change worker address',
  'change peer id',
  'submit windowed post',
  'precommit sector',
  'prove commit sector',
  'extend sector expiration',
  'terminate sectors',
  'declare faults',
  'declare faults recovered',
  'on deferred cron event',
  'check sector proven',
  'apply rewards',
  'report consensus fault',
  'withdraw balance',
  'confirm sector proofs valid',
  'change multiaddress',
  'compact partitions',
  'compact sector numbers',
  'confirm update worker key',
  'repay debt',
  'change owner address',
  'dispute windowed post',
  'precommit sector batch',
  'prove commit aggregate',
  'prove replica updates'
]
